#!/bin/bash

# Prompt the user for the WordPress site path
read -p "Enter the path to the WordPress site: " WORDPRESS_SITE_PATH

# Extract the WordPress site from the server origin
cd $WORDPRESS_SITE_PATH
zip -r $WORDPRESS_SITE_PATH.zip .

# Extract the BDD from the WordPress site
MYSQL_HOST="localhost"
MYSQL_USER="root"
MYSQL_PASSWORD="password"
MYSQL_DATABASE="wordpress_bdd"

mysql -u $MYSQL_USER -p$MYSQL_PASSWORD -h $MYSQL_HOST $MYSQL_DATABASE < $WORDPRESS_SITE_PATH/wp-config

# Transfer the .zip and .sql files to the destination server
scp $WORDPRESS_SITE_PATH.zip user@destination_server:/volumen/wp/
scp $WORDPRESS_SITE_PATH.sql user@destination_server:/volumen/db/
