# networks:
#   reevolutiva_net:
#     external: true

services:
  
  db_devpm:
    cpus: ${DEMYX_APP_DB_CPU}
    environment:
      - DEMYX_DOMAIN=${DEMYX_APP_DOMAIN}
      - MARIADB_CHARACTER_SET_SERVER=${MARIADB_CHARACTER_SET_SERVER}
      - MARIADB_COLLATION_SERVER=${MARIADB_COLLATION_SERVER}
      - MARIADB_DATABASE=${WORDPRESS_DB_NAME}
      - MARIADB_DEFAULT_CHARACTER_SET=${MARIADB_DEFAULT_CHARACTER_SET}
      - MARIADB_DOMAIN=${DEMYX_APP_DOMAIN}
      - MARIADB_INNODB_BUFFER_POOL_SIZE=${MARIADB_INNODB_BUFFER_POOL_SIZE}
      - MARIADB_INNODB_DATA_FILE_PATH=${MARIADB_INNODB_DATA_FILE_PATH}
      - MARIADB_INNODB_FLUSH_LOG_AT_TRX_COMMIT=${MARIADB_INNODB_FLUSH_LOG_AT_TRX_COMMIT}
      - MARIADB_INNODB_LOCK_WAIT_TIMEOUT=${MARIADB_INNODB_LOCK_WAIT_TIMEOUT}
      - MARIADB_INNODB_LOG_BUFFER_SIZE=${MARIADB_INNODB_LOG_BUFFER_SIZE}
      - MARIADB_INNODB_LOG_FILE_SIZE=${MARIADB_INNODB_LOG_FILE_SIZE}
      - MARIADB_INNODB_USE_NATIVE_AIO=${MARIADB_INNODB_USE_NATIVE_AIO}
      - MARIADB_KEY_BUFFER_SIZE=${MARIADB_KEY_BUFFER_SIZE}
      - MARIADB_MAX_ALLOWED_PACKET=${MARIADB_MAX_ALLOWED_PACKET}
      - MARIADB_MAX_CONNECTIONS=${MARIADB_MAX_CONNECTIONS}
      - MARIADB_MYISAM_SORT_BUFFER_SIZE=${MARIADB_MYISAM_SORT_BUFFER_SIZE}
      - MARIADB_NET_BUFFER_SIZE=${MARIADB_NET_BUFFER_SIZE}
      - MARIADB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MARIADB_READ_BUFFER=${MARIADB_READ_BUFFER}
      - MARIADB_READ_BUFFER_SIZE=${MARIADB_READ_BUFFER_SIZE}
      - MARIADB_READ_RND_BUFFER_SIZE=${MARIADB_READ_RND_BUFFER_SIZE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_SERVER_ID=${MARIADB_SERVER_ID}
      - MARIADB_SORT_BUFFER_SIZE=${MARIADB_SORT_BUFFER_SIZE}
      - MARIADB_TABLE_OPEN_CACHE=${MARIADB_TABLE_OPEN_CACHE}
      - MARIADB_USERNAME=${WORDPRESS_DB_USER}
      - MARIADB_WRITE_BUFFER=${MARIADB_WRITE_BUFFER}
      - TZ=America/Santiago
    image: demyx/mariadb
    mem_limit: ${DEMYX_APP_DB_MEM}
    networks:
      - reevolutiva_net
    restart: unless-stopped
    volumes:
      - /home/hosting/wpdev/db/:/demyx
      - /home/hosting/wpdev/log/:/var/log/demyx
  wp_devpm:
    #cpus: ${DEMYX_APP_WP_CPU}
    ports:
      - 5173:5173
    depends_on:
      - db_${DEMYX_APP_ID}
    environment:
      - DEMYX_ADMIN_IP=${DEMYX_APP_OLS_ADMIN_IP}
      - DEMYX_ADMIN_PASSWORD=${DEMYX_APP_OLS_ADMIN_PASSWORD}
      - DEMYX_ADMIN_USERNAME=${DEMYX_APP_OLS_ADMIN_USERNAME}
      - DEMYX_BASIC_AUTH_PASSWORD=${DEMYX_APP_AUTH_PASSWORD}
      - DEMYX_BASIC_AUTH_USERNAME=${DEMYX_APP_AUTH_USERNAME}
      - DEMYX_BASIC_AUTH_WP=${DEMYX_APP_AUTH_WP}
      - DEMYX_CACHE=${DEMYX_APP_CACHE}
      - DEMYX_CLIENT_THROTTLE_BANDWIDTH_IN=${DEMYX_APP_OLS_CLIENT_THROTTLE_BANDWIDTH_IN}
      - DEMYX_CLIENT_THROTTLE_BANDWIDTH_OUT=${DEMYX_APP_OLS_CLIENT_THROTTLE_BANDWIDTH_OUT}
      - DEMYX_CLIENT_THROTTLE_BAN_PERIOD=${DEMYX_APP_OLS_CLIENT_THROTTLE_BAN_PERIOD}
      - DEMYX_CLIENT_THROTTLE_BLOCK_BAD_REQUEST=${DEMYX_APP_OLS_CLIENT_THROTTLE_BLOCK_BAD_REQUEST}
      - DEMYX_CLIENT_THROTTLE_DYNAMIC=${DEMYX_APP_OLS_CLIENT_THROTTLE_DYNAMIC}
      - DEMYX_CLIENT_THROTTLE_GRACE_PERIOD=${DEMYX_APP_OLS_CLIENT_THROTTLE_GRACE_PERIOD}
      - DEMYX_CLIENT_THROTTLE_HARD_LIMIT=${DEMYX_APP_OLS_CLIENT_THROTTLE_HARD_LIMIT}
      - DEMYX_CLIENT_THROTTLE_SOFT_LIMIT=${DEMYX_APP_OLS_CLIENT_THROTTLE_SOFT_LIMIT}
      - DEMYX_CLIENT_THROTTLE_STATIC=${DEMYX_APP_OLS_CLIENT_THROTTLE_STATIC}
      - DEMYX_APP_OLS_CRAWLER_LOAD_LIMIT=${DEMYX_APP_OLS_CRAWLER_LOAD_LIMIT}
      - DEMYX_APP_OLS_CRAWLER_USLEEP=${DEMYX_APP_OLS_CRAWLER_USLEEP}
      - DEMYX_CRON=${DEMYX_APP_CRON}
      - DEMYX_CRON_LOGROTATE_INTERVAL="${DEMYX_APP_CRON_LOGROTATE_INTERVAL}"
      - DEMYX_CRON_WP_INTERVAL="${DEMYX_APP_CRON_WP_INTERVAL}"
      - DEMYX_DB_HOST=${WORDPRESS_DB_HOST}
      - DEMYX_DB_NAME=${WORDPRESS_DB_NAME}
      - DEMYX_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - DEMYX_DB_USERNAME=${WORDPRESS_DB_USER}
      - DEMYX_DOMAIN=${DEMYX_APP_DOMAIN}
      - DEMYX_LOGROTATE=${DEMYX_APP_LOGROTATE}
      - DEMYX_LOGROTATE_INTERVAL=${DEMYX_APP_LOGROTATE_INTERVAL}
      - DEMYX_LOGROTATE_SIZE=${DEMYX_APP_LOGROTATE_SIZE}
      - DEMYX_LSAPI_AVOID_FORK=${DEMYX_APP_OLS_LSAPI_AVOID_FORK}
      - DEMYX_LSAPI_CHILDREN=${DEMYX_APP_OLS_LSAPI_CHILDREN}
      - DEMYX_LSAPI_MAX_IDLE=${DEMYX_APP_OLS_LSAPI_MAX_IDLE}
      - DEMYX_LSAPI_MAX_PROCESS_TIME=${DEMYX_APP_OLS_LSAPI_MAX_PROCESS_TIME}
      - DEMYX_LSAPI_MAX_REQS=${DEMYX_APP_OLS_LSAPI_MAX_REQS}
      - DEMYX_LSPHP=${DEMYX_APP_OLS_LSPHP}
      - DEMYX_MAX_EXECUTION_TIME=${DEMYX_APP_PHP_MAX_EXECUTION_TIME}
      - DEMYX_MEMORY=${DEMYX_APP_PHP_MEMORY}
      - DEMYX_OPCACHE=${DEMYX_APP_PHP_OPCACHE}
      - DEMYX_PROTO=http
      - DEMYX_RECAPTCHA_CONNECTION_LIMIT=${DEMYX_APP_OLS_RECAPTCHA_CONNECTION_LIMIT}
      - DEMYX_RECAPTCHA_ENABLE=${DEMYX_APP_OLS_RECAPTCHA_ENABLE}
      - DEMYX_RECAPTCHA_TYPE=${DEMYX_APP_OLS_RECAPTCHA_TYPE}
      - DEMYX_TUNING_CONNECTION_TIMEOUT=${DEMYX_APP_OLS_TUNING_CONNECTION_TIMEOUT}
      - DEMYX_TUNING_KEEP_ALIVE_TIMEOUT=${DEMYX_APP_OLS_TUNING_KEEP_ALIVE_TIMEOUT}
      - DEMYX_TUNING_MAX_CONNECTIONS=${DEMYX_APP_OLS_TUNING_MAX_CONNECTIONS}
      - DEMYX_TUNING_MAX_KEEP_ALIVE=${DEMYX_APP_OLS_TUNING_MAX_KEEP_ALIVE}
      - DEMYX_TUNING_SMART_KEEP_ALIVE=${DEMYX_APP_OLS_TUNING_SMART_KEEP_ALIVE}
      - DEMYX_UPLOAD_LIMIT=${DEMYX_APP_UPLOAD_LIMIT}
      - DEMYX_WP_EMAIL=${WORDPRESS_USER_EMAIL}
      - DEMYX_WP_PASSWORD=${WORDPRESS_USER_PASSWORD}
      - DEMYX_WP_USERNAME=${WORDPRESS_USER}
      - DEMYX_XMLRPC=${DEMYX_APP_XMLRPC}
      - TZ=America/Santiago
      
    hostname: ${DEMYX_APP_COMPOSE_PROJECT}
    image: wpnode
    labels:
      - "traefik.enable=true"
      
      # HTTP
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-http.rule=Host(`${DEMYX_APP_DOMAIN}`)"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-http.entrypoints=http"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-http.service=${DEMYX_APP_COMPOSE_PROJECT}-http-port"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-http.priority=10"
      # - "traefik.http.services.${DEMYX_APP_COMPOSE_PROJECT}-http-port.loadbalancer.server.port=80"
      
      # HTTPS
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https.rule=Host(`${DEMYX_APP_DOMAIN}`)"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https.entrypoints=https"
      # - traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https.tls=true
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https.tls.certresolver=reevolutivaresolver"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https.service=${DEMYX_APP_COMPOSE_PROJECT}-https-port"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https.priority=10"
      # - "traefik.http.services.${DEMYX_APP_COMPOSE_PROJECT}-https-port.loadbalancer.server.port=80"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https.tls.domains[0].main=${DEMYX_APP_DOMAIN}"

      # # HTTPS Router for Port 5173
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https-dev.rule=Host(`${DEMYX_APP_DOMAIN}`) && PathPrefix(`/dev`)"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https-dev.entrypoints=https"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https-dev.tls=true"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https-dev.tls.certresolver=reevolutivaresolver"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https-dev.service=${DEMYX_APP_COMPOSE_PROJECT}-https-dev-port"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https-dev.priority=20"
      # - "traefik.http.services.${DEMYX_APP_COMPOSE_PROJECT}-https-dev-port.loadbalancer.server.port=5173"
      # - "traefik.http.routers.${DEMYX_APP_COMPOSE_PROJECT}-https.tls.domains[0].main=${DEMYX_APP_DOMAIN}"
      
    #mem_limit: ${DEMYX_APP_WP_MEM}
    networks:
      - reevolutiva_net
    restart: unless-stopped
    volumes:
      - /home/hosting/wpdev/wp/:/demyx
      - /home/hosting/wpdev/custom/:/etc/demyx/custom
      - /home/hosting/wpdev/log/:/var/log/demyx